### ISSUE TITLE
Pizza Productivity: Work tables not always rendered for all active participants

### ISSUE THREAD

**Issue by jugglinmike** [councilforeconed/interactive-activities#129] opened 2015-03-14 21:21 UTC
As originally reported by Chris Bujara:

> Work tables and ingredients are sometimes not rendered for participants
> that should be active in a round. The participant will see a “get ready”
> message at the start of the round, instead of “you’re sitting this one
> out”, but when the round starts, they have no work table and can’t
> participate.

**Comment by jugglinmike** [comment] 2015-03-15 21:44
I'm not able to reproduce this bug. Here are some of the things I've tried:

- **first round**: joining a new room in 4 tabs
- **first round**: joining a new room in 4 tabs, leaving in 3 tabs, then joining with 3 additional tabs
- **first round**: joining a new room in 4 tabs, **second round**: joining in 4 additional tabs
- **first round**: joining a new room in 4 tabs and leaving in 3 tabs, **second round**: joining in 3 additional tabs

It sounds like it's an intermittent problem (and likely hard to pin down), but any specific steps that trigger the behavior would be helpful.

**Comment by cbujara** [comment] 2015-03-15 22:37
?Thanks, Mike. Will do some testing and see what I can figure out.

________________________________

**Comment by cbujara** [comment] 2015-06-17 21:13
Can't reproduce issue, and believe it was resolved by https://github.com/councilforeconed/interactive-activities/issues/130

**Closed by cbujara** 2015-06-17 21:13 UTC
Labels: bug
